## TODO: Switch owner to pod
apiVersion: v1
kind: Pod
metadata:
  labels:
    job: {{ .Values.buildkite.job }}
    db: memcached
  ownerReferences:
  - apiVersion: batch/v1
    kind: Pod
    name: {{ .Values.buildkite.pod }}
    uid: {{ .Values.buildkite.pod_uid }}
  name: memcached-{{ .Values.buildkite.job }}
  namespace: {{ .Values.buildkite.namespace }}
spec:
  containers:
  - image: memcached:latest
    name: memcached
    ports:
    - containerPort: 11211
    readinessProbe:
      tcpSocket:
        port: 11211
    resources:
      requests:
        cpu: 500m
        memory: 128Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  ownerReferences:
  - apiVersion: batch/v1
    kind: Pod
    name: {{ .Values.buildkite.pod }}
    uid: {{ .Values.buildkite.pod_uid }}
  labels:
    job: {{ .Values.buildkite.job }}
  name: memcache-{{ .Values.buildkite.job }}
  namespace: {{ .Values.buildkite.namespace }}
spec:
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    job: {{ .Values.buildkite.job }}
    db: memcached