apiVersion: v1
kind: Pod
metadata:
  labels:
    job: {{ .Values.buildkite.job }}
    db: postgres
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: {{ .Values.buildkite.pod }}
    uid: {{ .Values.buildkite.pod_uid }}
  name: postgres-{{ .Values.buildkite.job }}
  namespace: {{ .Values.buildkite.namespace }}
spec:
  containers:
  - image: postgres:latest
    name: postgres
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
    readinessProbe:
      tcpSocket:
        port: 5432
    resources:
      requests:
        cpu: 500m
        memory: 128Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: {{ .Values.buildkite.pod }}
    uid: {{ .Values.buildkite.pod_uid }}
  labels:
    job: {{ .Values.buildkite.job }}
  name: postgres-{{ .Values.buildkite.job }}
  namespace: {{ .Values.buildkite.namespace }}
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    job: {{ .Values.buildkite.job }}
    db: postgres