apiVersion: v1
kind: Pod
metadata:
  labels:
    job: {{ .Values.buildkite.job }}
    db: redis
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: {{ .Values.buildkite.pod }}
    uid: {{ .Values.buildkite.pod_uid }}
  name: redis-{{ .Values.buildkite.job }}
  namespace: {{ .Values.buildkite.namespace }}
spec:
  containers:
  - image: redis:latest
    name: redis
    ports:
    - containerPort: 6379
    readinessProbe:
      tcpSocket:
        port: 6379
    resources:
      requests:
        cpu: 500m
        memory: 128Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: {{ .Values.buildkite.pod }}
    uid: {{ .Values.buildkite.pod_uid }}
  labels:
    job: {{ .Values.buildkite.job }}
  name: redis-{{ .Values.buildkite.job }}
  namespace: {{ .Values.buildkite.namespace }}
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    job: {{ .Values.buildkite.job }}
    db: redis