steps:
  - label: ":kubernetes: test execution"
    key: parallel-step
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            serviceAccountName: agent-stack-k8s
            containers:
              - name: manifests-apply
                image: portainer/kubectl-shell:latest
                command: [.buildkite/steps/apply.sh]
                env:
                - name: BUILDKITE_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: BUILDKITE_K8S_JOB_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['job-name']
                - name: BUILDKITE_K8S_POD
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: BUILDKITE_K8S_POD_UID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.uid
              - name: parallel-specs
                image: $BUILT_IMAGE
                command: [scripts/ci/parallel_specs.sh]
