steps:
  - label: ":docker: build image"
    key: parallel-step
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            serviceAccountName: agent-stack-k8s
            containers:
              - name: manifests
                image: bhgedigital/envsubst
                command: [.buildkite/steps/manifests.sh]
                env:
                - name: BUILDKITE_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: BUILDKITE_K8S_JOB_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['job-name']
                - name: BUILDKITE_SHELL
                  value: "/bin/sh -e"
              - name: manifests-apply
                image: bitnami/kubectl
                command: [.buildkite/steps/apply.sh]
              - name: docker
                image: $BUILT_IMAGE
                command: [scripts/ci/parallel_specs.sh]
                env:
                - name: PGHOST
                  value: postgres-$BUILDKITE_JOB_ID
                - name: PGUSER
                  value: postgres
                - name: REDIS_URL
                  value: redis://redis-$BUILDKITE_JOB_ID
                - name: MEMCACHE_SERVERS
                  value: memcache-$BUILDKITE_JOB_ID
