steps:
  - label: ":docker: build image"
    key: image
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - name: docker
                image: crazymax/docker:latest
                command: [.buildkite/steps/image.sh]
                volumeMounts:
                - name: buildkit-client
                  mountPath: /buildkit/certs
                - name: docker-creds
                  mountPath: /creds/.docker
            volumes:
            - name: buildkit-client
              secret:
                secretName: buildkit-client-certs
            - name: docker-creds
              secret:
                secretName: dockerconfigjson
  - label: "pipeline-upload parallel"
    depends_on: image
    command: .buildkite/steps/parallel.sh
    agents:
      queue: kubernetes
