apiVersion: v1
kind: Pod
metadata:
  labels:
    job: $BUILDKITE_JOB_ID
    db: memcached
  ownerReferences:
  - apiVersion: batch/v1
    kind: Job
    name: $BUILDKITE_K8S_JOB_NAME
    uid: $BUILDKITE_K8S_JOB_UID
  name: memcached
  namespace: $BUILDKITE_NAMESPACE
spec:
  containers:
  - image: memcached:latest
    name: memcached
    containerPort: 11211
    readinessProbe:
      tcpSocket:
        port: 11211
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  ownerReferences:
  - apiVersion: batch/v1
    kind: Job
    name: $BUILDKITE_K8S_JOB_NAME
    uid: $BUILDKITE_K8S_JOB_UID
  labels:
    job: $BUILDKITE_JOB_ID
  name: memcache-$BUILDKITE_JOB_ID
  namespace: buildkite
spec:
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    job: $BUILDKITE_JOB_ID
    db: memcached