apiVersion: v1
kind: Pod
metadata:
  labels:
    job: $BUILDKITE_JOB_ID
    db: postgres
  ownerReferences:
  - apiVersion: batch/v1
    kind: Job
    name: $BUILDKITE_K8S_JOB_NAME
    uid: $BUILDKITE_K8S_JOB_UID
  name: postgres
  namespace: $BUILDKITE_NAMESPACE
spec:
  containers:
  - image: postgres:latest
    name: postgres
    containerPort: 5432
    readinessProbe:
      tcpSocket:
        port: 5432
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  ownerReferences:
  - apiVersion: batch/v1
    kind: Job
    name: $BUILDKITE_K8S_JOB_NAME
    uid: $BUILDKITE_K8S_JOB_UID
  labels:
    job: $BUILDKITE_JOB_ID
  name: postgres-$BUILDKITE_JOB_ID
  namespace: buildkite
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    job: $BUILDKITE_JOB_ID
    db: postgres