apiVersion: v1
kind: Pod
metadata:
  labels:
    job: $BUILDKITE_JOB_ID
    db: redis
  ownerReferences:
  - apiVersion: batch/v1
    kind: Job
    name: $BUILDKITE_K8S_JOB_NAME
    uid: $BUILDKITE_K8S_JOB_UID
  name: redis
  namespace: $BUILDKITE_NAMESPACE
spec:
  containers:
  - image: redis:latest
    name: redis
    containerPort: 6379
    readinessProbe:
      tcpSocket:
        port: 6379
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  ownerReferences:
  - apiVersion: batch/v1
    kind: Job
    name: $BUILDKITE_K8S_JOB_NAME
    uid: $BUILDKITE_K8S_JOB_UID
  labels:
    job: $BUILDKITE_JOB_ID
  name: redis-$BUILDKITE_JOB_ID
  namespace: buildkite
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    job: $BUILDKITE_JOB_ID
    db: redis